title: bille.dev
email: toto@bille.dev
baseurl: 
url: "https://bille.dev"
github_username:  tbille

collections:
  posts:
    permalink: /blog/:slug

plugins:
  - jekyll-feed
  - jekyll-sitemap

show_drafts: true

feed:
  include_drafts: false
  path: /blog/feed.atom