title: bille.dev blog
description: Micro-blog where I talk about recent discoveries, mostly around coffee, photography and technology.
author: Thomas (toto) Bille
email: toto@bille.dev
baseurl: 
url: "https://bille.dev"
github_username:  tbille

collections:
  posts:
    permalink: /blog/:slug

plugins:
  - jekyll-sitemap

show_drafts: true
